name: Policy-as-Code Check

on: [push, pull_request]

jobs:
  vet_code:
    runs-on: ubuntu-latest
    steps:
      # 1. Download your code
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

# 2. Install Terraform (The Builder)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      # 3. Install Google Cloud SDK (The Inspector)
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'beta,terraform-tools'

# 4. Run the Checks
      - name: Run Inspector
        run: |
          terraform init
          terraform plan -out=test.tfplan
          terraform show -json test.tfplan > test.json
          echo "--- DEBUG: CONTENT OF test.json ---"
          head -n 5 test.json     # This will show us the first 5 lines
          gcloud beta terraform vet test.json --policy-library=.